# settings
site_name: Witch Love Wiki
site_url: https://witch-love.github.io/
repo_url: https://github.com/Witch-Love
repo_name: Witch Love (GitHub)
copyright: '&copy; All nipahs reserved'
site_dir: wiki
extra_javascript:
  - js/version.js

# navigation
nav:
  - index.md
  - <b>Umineko</b>:
    - Kurulum:
      - umineko/installation.md
      - umineko/tr-installation.md
  - <b>Higurashi</b>:
    - Kurulum:
      - higurashi/tr-installation.md
  - Website: 'https://witch-love.github.io/'
  - Bağış: 'donation.md'

# extra
extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/jyD5jn9Vpd
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@Singularityy

# plugins
plugins:
  - search

# theme
theme:
  name: material
  language: tr
  favicon: img/favicon.ico
  features:
    - navigation.path
    - navigation.footer
    - content.tabs.link
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Aydınlık temaya geç
    - scheme: default
      accent: amber
      toggle:
        icon: material/weather-night
        name: Karanlık temaya geç

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
      permalink_title: Bağlantıyı kopyala
      toc_depth: 5