# settings
site_name: Witch Love Wiki
site_description: Umineko başta olmak üzere, sevgi ve saygı duyduğumuz Türkçe olmayan eserleri büyük bir özenle Türkçe'ye çevirerek daha fazla insana ulaştırabilmeyi amaçlıyoruz.
site_url: https://witch-love.com/wiki
repo_url: https://github.com/Witch-Love
repo_name: Witch Love (GitHub)
copyright: '&copy; 2025 All nipahs reserved'
site_dir: wiki
edit_uri: witch-love.github.io/edit/main/mkdocs/docs

# navigation
nav:
  - index.md
  - Umineko:
    - umineko/index.md
    - Kurulum:
      - 1. Umineko Project: umineko/installation.md
      - 2. Türkçe Patch: umineko/tr-installation.md
    - Katkıda Bulunma:
      - umineko/contributing/info.md
      - umineko/contributing/rules.md
  - Higurashi:
    - higurashi/index.md
    - higurashi/installation.md
    - Katkıda Bulunma:
      - higurashi/contributing/info.md
      - higurashi/contributing/rules.md
  - For Developers:
    - Umineko Project:
      - umineko/creating-translations.md
  - donation.md
  - contact.md

# extra
extra:
  homepage: https://witch-love.com/
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/jyD5jn9Vpd
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@Singularityy
  status:
    new: Yeni
    deprecated: Kullanım dışı
    draft: Taslak
  analytics:
    provider: google
    property: G-D9MFM5S3BH
extra_javascript:
  - js/custom.js
extra_css:
  - css/admonitions.css
  - css/status.css
  - css/custom.css
  - css/image_modals.css

# plugins
plugins:
  - search
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: timeago
      locale: tr
  - git-committers:
      enabled: !ENV [CI, false]
      repository: Witch-Love/witch-love.github.io
      docs_path: mkdocs/docs/
      branch: main

# theme
theme:
  name: material
  language: tr
  custom_dir: overrides
  favicon: img/favicon.ico
  icon:
    logo: butterfly
    edit: material/pencil
  features:
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Aydınlık temaya geç
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Karanlık temaya geç

markdown_extensions:
  - admonition
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      title: İçindekiler
      permalink: ⚓︎
      permalink_title: Bağlantıyı kopyala
      toc_depth: 5

watch:
  - overrides