site_name: Witch Love - Wiki
site_url: https://witch-love.github.io/
repo_url: https://github.com/Witch-Love
repo_name: Witch Love (Organization)
copyright: All nipahs reserved
site_dir: wiki
theme:
  name: material
  language: tr
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Aydınlık temaya geç
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Karaklık temaya geç