# settings
site_name: Witch Love Wiki
site_url: https://witch-love.github.io/wiki
repo_url: https://github.com/Witch-Love
repo_name: Witch Love (GitHub)
copyright: '&copy; 2024 All nipahs reserved'
site_dir: wiki
edit_uri: witch-love.github.io/edit/main/mkdocs/docs

# navigation
nav:
  - index.md
  - <b>Umineko</b>:
    - umineko/index.md
    - Kurulum:
      - umineko/installation.md
      - umineko/tr-installation.md
    - Katkıda Bulunmak:
      - umineko/contributing/info.md
      - umineko/contributing/rules.md
  - <b>Higurashi</b>:
    - higurashi/index.md
    - higurashi/installation.md
    - Katkıda Bulunmak:
      - higurashi/contributing/info.md
      - higurashi/contributing/rules.md
  - donation.md
  - contact.md

# extra
extra:
  homepage: https://witch-love.github.io/
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/jyD5jn9Vpd
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@Singularityy
extra_javascript:
  - js/version.js
extra_css:
  - css/admonitions.css
  - css/custom.css

# plugins
plugins:
  - search
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: timeago
      locale: tr
  - git-committers:
      enabled: !ENV [CI, false]
      repository: Witch-Love/witch-love.github.io
      docs_path: mkdocs/docs/
      branch: main

# theme
theme:
  name: material
  language: tr
  custom_dir: overrides
  favicon: img/favicon.ico
  icon:
    logo: material/book
    edit: material/pencil 
    view: material/eye
  features:
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Aydınlık temaya geç
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Karanlık temaya geç

markdown_extensions:
  - admonition
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
      permalink_title: Bağlantıyı kopyala
      toc_depth: 5
  - markdown_include.include:
      base_path: snippets